### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by KorigamiK** [frozein/VkGalaxy#1]
Hi, I'm trying out vulkan myself and I found you project very informative. However I run into this warning
when I try to close the application on linux.

Do you reckon any specific reasons this might be happening? Can we fix this?

```sh
Ξ Debug/bin git:(main) ▶ ./vkgalaxy
VKH MESSAGE in vkh.c at line 1104 - "initlalizing GLFW..."

VKH MESSAGE in vkh.c at line 1135 - "creating Vulkan instance..."

VKH MESSAGE in vkh.c at line 1318 - "picking physical device..."

VKH MESSAGE in vkh.c at line 1449 - "creating Vulkan device..."

VKH MESSAGE in vkh.c at line 1526 - "creating Vulkan swapchain..."

VKH MESSAGE in vkh.c at line 1649 - "creating command pool..."

VKH MESSAGE in vkh.c at line 1667 - "destroying command pool..."

VKH MESSAGE in vkh.c at line 1636 - "destroying Vulkan swapchain..."

VKH MESSAGE in vkh.c at line 1519 - "destroying Vulkan device..."

VKH MESSAGE in vkh.c at line 1297 - "destroying Vulkan instance..."

VKH MESSAGE in vkh.c at line 1127 - "quitting GLFW..."


=================================================================
==23434==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5120 byte(s) in 8 object(s) allocated from:
    #0 0x7f7eb38e007a in __interceptor_realloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:85
    #1 0x7f7eb246910b  (/usr/lib/libfontconfig.so.1+0x2110b) (BuildId: 6aec681ec5b2fb80f3a60e3cf3d75abac345c9b3)

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7f7eb38e0cc1 in __interceptor_calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x7f7eb3ee03df in libdecor_plugin_init (/usr/lib/../lib/libdecor-0.so.0+0x53df) (BuildId: 39cc32d3d09acbcd38002d441bc58273cbbd1d64)

Direct leak of 6 byte(s) in 1 object(s) allocated from:
    #0 0x7f7eb386c32a in __interceptor_strdup /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x7f7eb3709c30  (/usr/lib/libdecor/plugins-1/libdecor-gtk.so+0x6c30) (BuildId: cd3e0be65d3825af82b32369b09c9fc0371b82c6)

Indirect leak of 19328 byte(s) in 604 object(s) allocated from:
    #0 0x7f7eb38e1359 in __interceptor_malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f7eb2454ac0  (/usr/lib/libfontconfig.so.1+0xcac0) (BuildId: 6aec681ec5b2fb80f3a60e3cf3d75abac345c9b3)

Indirect leak of 8052 byte(s) in 588 object(s) allocated from:
    #0 0x7f7eb386c32a in __interceptor_strdup /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x7f7eb2454213  (/usr/lib/libfontconfig.so.1+0xc213) (BuildId: 6aec681ec5b2fb80f3a60e3cf3d75abac345c9b3)

Indirect leak of 4960 byte(s) in 155 object(s) allocated from:
    #0 0x7f7eb38e0cc1 in __interceptor_calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x7f7eb246d47d  (/usr/lib/libfontconfig.so.1+0x2547d) (BuildId: 6aec681ec5b2fb80f3a60e3cf3d75abac345c9b3)

Indirect leak of 3648 byte(s) in 114 object(s) allocated from:
    #0 0x7f7eb38e0cc1 in __interceptor_calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x7f7eb2468b0c  (/usr/lib/libfontconfig.so.1+0x20b0c) (BuildId: 6aec681ec5b2fb80f3a60e3cf3d75abac345c9b3)

Indirect leak of 707 byte(s) in 93 object(s) allocated from:
    #0 0x7f7eb386c32a in __interceptor_strdup /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x7f7eb24688a8 in FcValueSave (/usr/lib/libfontconfig.so.1+0x208a8) (BuildId: 6aec681ec5b2fb80f3a60e3cf3d75abac345c9b3)

Indirect leak of 512 byte(s) in 16 object(s) allocated from:
    #0 0x7f7eb38e0cc1 in __interceptor_calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x7f7eb24689c0  (/usr/lib/libfontconfig.so.1+0x209c0) (BuildId: 6aec681ec5b2fb80f3a60e3cf3d75abac345c9b3)

Indirect leak of 192 byte(s) in 4 object(s) allocated from:
    #0 0x7f7eb38e1359 in __interceptor_malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f7eb245e988 in FcLangSetCopy (/usr/lib/libfontconfig.so.1+0x16988) (BuildId: 6aec681ec5b2fb80f3a60e3cf3d75abac345c9b3)

SUMMARY: AddressSanitizer: 42533 byte(s) leaked in 1584 allocation(s).
```

**Comment by frozein** [comment]
I have looked into this for a while, and it seems to be an issue with Vulkan. A few people have noted similar issues online, with even very simple programs leaking memory from Vulkan library functions. If anyone finds a fix for this I'd love to hear it.
